### ISSUE TITLE
Error on first command when not using offline mode

### ISSUE THREAD

**Issue by davidboden** [tclavier/docker-scriptcraft#5]
On both my local Windows PC and an Amazon EC2 instance, everything works fine if I run:

```
$ docker run -p 25565:25565 -it -e ONLINE_MODE=false -e WORLD_TYPE=DEFAULT -v /c/Users/MyUsername/scriptcraft:/minecraft tclavier/scriptcraft
```

However, if I leave off the -e ONLINE_MODE=false and just run:

```
$ docker run -p 25565:25565 -it -e WORLD_TYPE=DEFAULT -v /c/Users/MyUsername/scriptcraft:/minecraft tclavier/scriptcraft
```

I get an error message when attempting to run the first command. After that, I just get "unknown command" on the Minecraft client:

```
> /js rainbow()
[13:51:25] [ScriptCraft] [ERROR]: Error while trying to evaluate javascript: rainbow(), Error: java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer]
javax.script.ScriptException: java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer] in <eval> at line number 630 at column number 8
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:389)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at org.scriptcraftjs.canarymod.ScriptCraftPlugin.executeCommand(ScriptCraftPlugin.java:103)
        at org.scriptcraftjs.canarymod.ScriptCraftPlugin.jsCommand(ScriptCraftPlugin.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:322)
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:103)
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:186)
        at net.canarymod.api.CanaryServer.consoleCommand(CanaryServer.java:172)
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:140)
Caused by: <eval>:630:8 java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer]
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$258$\^eval\_.__onEnable$__onCommand(<eval>:630)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:614)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer]
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)>
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)        at jdk.nashorn.internal.scripts.Script$Recompilation$258$\^eval\_.__onEnable$__onCommand(<eval>:605)
        ... 17 more
Caused by: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer]
        at jdk.internal.dynalink.beans.OverloadedMethod.throwNoSuchMethod(OverloadedMethod.java:202)
        at jdk.nashorn.internal.scripts.Script$Recompilation$262$8477A$\^eval\_.L:1$getMousePos(<eval>:293)
        at jdk.nashorn.internal.scripts.Script$Recompilation$261$13394AAAAA$\^eval\_.L:1$Drone(<eval>:366)
        at jdk.nashorn.internal.scripts.Script$Recompilation$260$16449$\^eval\_.[13:51:25] [CanaryMod] [INFO] [MESSAGE]: Error while trying to evaluate javascript: rainbow(), Error: java.lang.RuntimeException: java.lang.NoSuchMethodException: None of the fixed arity signatures [(net.canarymod.api.entity.living.humanoid.Player), (net.canarymod.api.world.position.Location)] of method net.canarymod.LineTracer.<init> match the argument types [net.canarymod.api.CanaryServer]
>
        at jdk.nashorn.internal.scripts.Script$259$\^eval\_.:program(<eval>:1)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
```

Sorry if I'm making an obvious error?

**Comment by tclavier** [comment]
that work without docker ?

**Comment by davidboden** [comment]
Good point. I'd imagine that it's CanaryMod-related rather than specific to this Docker file.
